apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ydtu2phkb-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ydtu2phkb-java-quarkus-gitops